OperationTourCode/OTC

mashups/official/gen8stabmonsdoubles.tour
mashups/official/gen8stabmonslittlecup.tour

Updated STABmon Double to include bans HeatEdgeSword mentioned. Updated STABmons LC to include some previous mon restriction (geomancy, lovely kiss, tarrows)

DLC2 Update: Part 1

---

mashups/official/gen8caaamomons.tour

I finally figured it out how to actually unban Zygarde in CAAAmomons

Fix an issue where Zygarde is still banned

---

mashups/other/gen8flaaapped.tour
mashups/other/gen8inhubers.tour

Unbanned Zacian, Zamazenta, and Magearna

updated gen8flaaapped banlist, add power construct to gen8inhubers unbans

---

mashups/official/gen8tsaaa.tour

Absol, Bellossom and Tinted lens are removed, rest of the tour code is just tidied

Update gen8tsaaa to reflect bans

---

mashups/official/gen8tsaaa.tour

Ban guzzlord as per the TSAAA councils decision

Ban guzzlord in TSAAA

---

mashups/other/gen8zustaaab.tour

ZU STAAAB: Ban Type:Null, Rotom-Fan, Rotom-Frost; Restrict Surging Strikes

---

mashups/official/gen8tsaaa.tour

TSAAA updates corresponding to https://www.smogon.com/forums/threads/om-mashup-megathread.3657159/post-8820445

update gen8tsaaa as per new council bans and unbans

---

mashups/other/gen8skaaatch.tour

Added No Retreat, Transform, Regieleki
Removed unnecessary unban of Swoobat
Also fixed minor typographical error

Update SkAAAtch with Sketch bans

---

mashups/official/gen8stabmonslittlecup.tour

Also, sneaking the Porygon ban. I'm a snail to let this mon legal for year when i should've quickbanned it during early dlc1

Restricting Glacial Lance

---

metadata/aliases.txt

People try to ?start with these aliases all the time anyway

STAB n Mega: Add aliases

---

mashups/official/gen8almostanyabilitydoubles.tour

- Unbanned Cresselia
- Added Sleep Clause Mod
- Banned Stored Power
Request: https://www.smogon.com/forums/threads/om-mashup-megathread.3657159/post-8912908

AAA Doubles: Banlist Updates

---

mashups/official/gen8almostanyabilitylittlecup.tour

missing comma between Cherubi and Gothita

Fix minor issue

---

mashups/other/gen8hackmonschaos.tour

I don't even know why "!Sleep Clause" was in the tourcode--esp. considering that it should be Sleep Clause Mod if anything

Hackmons Chaos Cup: Fixed banlist

---

mashups/other/gen8tsinhe.tour

/tour new had an extra comma(s)

TS Inheritance: Fix Typo

---

mashups/official/gen8stabnmega.tour

Will merge once next week of trios is up

STAB n Mega: Restrict Keldeo

---

mashups/other/gen8sketchmonsubers.tour

Unrestricted Astral Barrage, Clangorous Soul, Extreme Speed, Secret Sword, and Wicked Blow

Sketch Ubers: Update Restrictions

---

mashups/official/gen8stabmonsdoubles.tour

https://www.smogon.com/forums/threads/om-mashup-megathread.3657159/post-8991108

STAB Doubles: Restrict Oblivion Wing

---

mashups/official/gen8aaadoublesbuiltin.tour
mashups/official/gen8almostanyabilitydoubles.tour
mashups/official/metadata/list.txt
metadata/aliases.txt

(Might need some changes depending on what Kris calls the LCotM format.)

Prepare a tour code for AAA Doubles LCotM

---

mashups/other/gen8crossevoag.tour

-challengeable format was also removed, adding as a mod

Adding Cross Evolution as Mod

---

mashups/other/gen8ggsp.tour

https://www.smogon.com/forums/threads/om-mashup-megathread-aaa-doubles-is-leaders-choice-for-november.3657159/page-27#post-9030327

Godly Power: Update Banlist and Resources

---

mashups/other/gen8ggsp.tour

https://www.smogon.com/forums/threads/om-mashup-megathread-aaa-doubles-is-leaders-choice-for-november.3657159/page-27#post-9034693

GGSP: Update with latest bans

---

mashups/other/gen8monobh.tour

https://www.smogon.com/forums/threads/om-mashup-megathread.3657159/post-9124457

Monotype BH: Add resources hub

---

mashups/other/gen8monobh.tour

https://www.smogon.com/forums/threads/om-mashup-megathread.3657159/post-9127857

Monotype BH: Ban Normalize

---

mashups/other/gen8randbatsmayhemsuddendeath.tour

Also displays what first blood rule does to limit confusion since its been brought up somewhat

Mayhem Sudden Death: use built in format

---

formats/gen8stabmnm.tour
formats/gen9stabmnm.tour
mashups/officialslist.txt
metadata/dynamicformatdescriptions.txt
metadata/list.txt

#RICEMAN: "Gen 9 Stabmons Mix and Mega  PR"
Created via Iolanthe on Sun, 11 Dec 2022 21:02:51 GMT.

(#RICEMAN) gen8stabmnm: Gen 9 Stabmons Mix and Mega  PR

---

formats/gen9ultramix.tour
metadata/list.txt

#RICEMAN: "Gen 9 Ultramix  PR"
Created via Iolanthe on Tue, 13 Dec 2022 01:49:45 GMT.

(#RICEMAN) gen9ultramix: Gen 9 Ultramix  PR

---

formats/gen9aaalc.tour
mashups/officialslist.txt
metadata/dynamicformatdescriptions.txt
metadata/list.txt

#RICEMAN: "Gen 9 Almost Any Ability Little Cup PR"
Created via Iolanthe on Tue, 13 Dec 2022 01:51:11 GMT.

(#RICEMAN) gen9aaalc: Gen 9 Almost Any Ability Little Cup PR

---

formats/gen9stabmnm.tour

#Ducky: "[Gen 9] STAB n Mega PR"
Created via Iolanthe on Tue, 13 Dec 2022 17:13:20 GMT.

(#Ducky) gen9stabmnm: [Gen 9] STAB n Mega PR

---

formats/gen9fortereevochaos.tour
metadata/list.txt

#Hisuian Zoroark: "Forte Reevo Chaos"
Created via Iolanthe on Thu, 26 Jan 2023 15:21:00 GMT.

(#Hisuian Zoroark) gen9fortereevochaos: Forte Reevo Chaos

---

formats/gen7convergencepokebilities.tour
metadata/list.txt

#Hisuian Zoroark: "Add Gen 7 Converge Poke"
Created via Iolanthe on Fri, 10 Feb 2023 02:18:30 GMT.

(#Hisuian Zoroark) gen7convergencepokebilities: Add Gen 7 Converge Poke

---

formats/gen9stabubers.tour

#RICEMAN: "Gen 9 Stabmons Ubers PR (Add Sleep Clause)"
Created via Iolanthe on Fri, 10 Feb 2023 01:03:10 GMT.

(#RICEMAN) gen9stabubers: Gen 9 Stabmons Ubers PR (Add Sleep Clause)

---

formats/gen9aaaubers.tour
metadata/list.txt

#HISUIAN ZOROARK!: "AAA Ubers Gen 9"
Created via Iolanthe on Mon, 06 Mar 2023 00:48:49 GMT.

(#HISUIAN ZOROARK!) gen9aaaubers: AAA Ubers Gen 9

---

formats/gen9tsaaa.tour

@longhiep341: "TSAAA with Pikachu banned"
Created via Iolanthe on Mon, 13 Mar 2023 19:36:10 GMT.

(@longhiep341) gen9tsaaa: TSAAA with Pikachu banned

---

formats/gen9capmnm.tour
metadata/list.txt

%Akoof: "adding tour code"
Created via Iolanthe on Thu, 16 Mar 2023 13:46:55 GMT.

(%Akoof) gen9capmnm: adding tour code

---

formats/gen9brokenmayhem.tour
metadata/list.txt

@Clastia: "adding tour code"
Created via Iolanthe on Fri, 17 Mar 2023 17:11:56 GMT.

(@Clastia) gen9brokenmayhem: adding tour code

---

formats/gen9fortestabaaa.tour
metadata/list.txt

#Hisuian Zoroark: "Fortestaaab"
Created via Iolanthe on Sat, 18 Mar 2023 22:40:01 GMT.

(#Hisuian Zoroark) gen9fortestabaaa: Fortestaaab

---

formats/gen9aaaag.tour
metadata/list.txt

@longhiep341: "Gen 9 AAA AG"
Created via Iolanthe on Wed, 22 Mar 2023 11:32:11 GMT.

(@longhiep341) gen9aaaag: Gen 9 AAA AG

---

formats/gen9ggmnm.tour

@Clas: "adding tour code"
Created via Iolanthe on Mon, 27 Mar 2023 22:18:26 GMT.

(@Clas) gen9ggmnm: adding tour code

---

formats/gen9tsaaa.tour

@longhiep341: "Ban Oricorio (All 4)"
Created via Iolanthe on Wed, 29 Mar 2023 14:15:47 GMT.

(@longhiep341) gen9tsaaa: Ban Oricorio (All 4)

---

formats/gen9inhrev.tour
formats/gen9inhrevmons.tour
metadata/list.txt

%TheTrueLtaker: "adding new tour code"
Created via Iolanthe on Fri, 31 Mar 2023 16:43:07 GMT.

(%TheTrueLtaker) gen9inhrevmons: adding new tour code

---

formats/gen9mixandconverge.tour
formats/gen9mnmconverge.tour
metadata/aliases.txt
metadata/list.txt

%TheTrueLtaker: "adding code"
Created via Iolanthe on Fri, 31 Mar 2023 16:46:24 GMT.

(%TheTrueLtaker) gen9mixandconverge: adding code

---

formats/gen7convergepoke.tour

%TheTrueLtaker: "updating bans"
Created via Iolanthe on Fri, 31 Mar 2023 18:25:37 GMT.

(%TheTrueLtaker) gen7convergepoke: updating bans

---

formats/gen9csflippedaaa.tour
formats/gen9reversegame.tour
metadata/aliases.txt
metadata/list.txt

@Clas: "adding tour code"
Created via Iolanthe on Sun, 02 Apr 2023 10:46:25 GMT.

(@Clas) gen9reversegame: adding tour code

---

formats/gen9capconverge.tour

@Hisuian Zoroark: "Ban things from tour"
Created via Iolanthe on Sat, 08 Apr 2023 03:44:02 GMT.

(@Hisuian Zoroark) gen9capconverge: Ban things from tour

---

formats/gen9chimerarandbats24.tour

&CringeMeta: "adding tour code"
Created via Iolanthe on Fri, 07 Apr 2023 12:47:35 GMT.

(&CringeMeta) gen9chimerarandbats24: adding tour code

---

formats/gen9capmnm.tour

#longhiep341: "Unban Vile Vial due to Tera ban"
Created via Iolanthe on Sun, 09 Apr 2023 12:42:59 GMT.

(#longhiep341) gen9capmnm: Unban Vile Vial due to Tera ban

---

formats/gen9randbtassuddendeath.tour
metadata/list.txt

@Clas: "adding code"
Created via Iolanthe on Tue, 02 May 2023 08:10:00 GMT.

(@Clas) gen9randbtassuddendeath: adding code

---

formats/gen9picaaa.tour
metadata/list.txt

%Akoof: "adding tour code"
Created via Iolanthe on Thu, 25 May 2023 18:18:11 GMT.

(%Akoof) gen9picaaa: adding tour code

---

formats/gen9picaaa.tour

%Akoof: "adding bans and fixing code error"
Created via Iolanthe on Fri, 26 May 2023 13:58:19 GMT.

(%Akoof) gen9picaaa: adding bans and fixing code error

---

formats/gen9picaaa.tour

%Akoof: "typo in code sun to land and primordal to primordial"
Created via Iolanthe on Tue, 30 May 2023 01:25:44 GMT.

(%Akoof) gen9picaaa: typo in code sun to land and primordal to primordial

---

formats/gen9mnmlc.tour
metadata/list.txt

@Clas: "adding tour code"
Created via Iolanthe on Sat, 01 Jul 2023 14:03:55 GMT.

(@Clas) gen9mnmlc: adding tour code

---

formats/gen9tdstabrevbt.tour
formats/gen9teradonation.tour
metadata/aliases.txt
metadata/list.txt

%Banded Body Press: "typechaos"
Created via Iolanthe on Sun, 30 Jul 2023 14:42:27 GMT.

(%Banded Body Press) gen9teradonation: typechaos

---

formats/gen9tdstabrevbt.tour
formats/gen9typechaos.tour
metadata/aliases.txt
metadata/list.txt

@placuszek: "typechaos"
Created via Iolanthe on Sun, 30 Jul 2023 18:37:30 GMT.

(@placuszek) gen9tdstabrevbt: typechaos

---

formats/gen9ggmnm.tour

@Clas: "updates code for post home"
Created via Iolanthe on Fri, 04 Aug 2023 21:35:55 GMT.

(@Clas) gen9ggmnm: updates code for post home

---

formats/gen9ungodlygift.tour
metadata/list.txt

%Banded Body Press: "ungg"
Created via Iolanthe on Sun, 13 Aug 2023 14:28:01 GMT.

(%Banded Body Press) gen9ungodlygift: ungg

---

formats/gen9stabmnm.tour

@Clas: "bans etern, restricts wake/gambit"
Created via Iolanthe on Sun, 13 Aug 2023 22:16:07 GMT.

(@Clas) gen9stabmnm: bans etern, restricts wake/gambit

---

formats/gen9stabmnm.tour

@Clas: "fixes zac-c legality, cant stop rsword legality issue until mnm stone restricts work"
Created via Iolanthe on Thu, 17 Aug 2023 11:57:04 GMT.

(@Clas) gen9stabmnm: fixes zac-c legality, cant stop rsword legality issue until mnm stone restricts work

---

formats/gen9camoconverge.tour
formats/gen9camovergence.tour
metadata/aliases.txt
metadata/list.txt

%TheTrueLtaker: "adding tour code"
Created via Iolanthe on Sat, 26 Aug 2023 20:06:03 GMT.

(%TheTrueLtaker) gen9camovergence: adding tour code

---

formats/gen9ggmnm.tour

@Clas: "frees etern bc its mistakenly banned"
Created via Iolanthe on Sat, 26 Aug 2023 23:05:07 GMT.

(@Clas) gen9ggmnm: frees etern bc its mistakenly banned

---

formats/gen8ssbchimera.tour
metadata/list.txt

%TheTrueLtaker: "adding tour code"
Created via Iolanthe on Sat, 26 Aug 2023 23:30:40 GMT.

(%TheTrueLtaker) gen8ssbchimera: adding tour code

---

formats/gen9mnmlc.tour

@Clas: "ban lucarionite, changed mnmlc to lcmnm"
Created via Iolanthe on Sun, 27 Aug 2023 13:55:03 GMT.

(@Clas) gen9mnmlc: ban lucarionite, changed mnmlc to lcmnm

---

formats/gen9stabmnm.tour

@Clas: "restricts luna"
Created via Iolanthe on Tue, 29 Aug 2023 17:31:14 GMT.

(@Clas) gen9stabmnm: restricts luna

---

formats/gen9stabmnm.tour

#placuszek: "ban za cyan crowned, restrict ptrip"
Created via Iolanthe on Sun, 03 Sep 2023 20:07:46 GMT.

(#placuszek) gen9stabmnm: ban za cyan crowned, restrict ptrip

---

formats/gen9absolutechaos.tour
metadata/list.txt

%TheTrueLtaker: "adding tour code"
Created via Iolanthe on Thu, 07 Sep 2023 01:54:22 GMT.

(%TheTrueLtaker) gen9absolutechaos: adding tour code

---

formats/gen9stabmnm.tour

#placuszek: "week5 slate"
Created via Iolanthe on Sun, 10 Sep 2023 19:55:14 GMT.

(#placuszek) gen9stabmnm: week5 slate

---

formats/gen8ggph.tour

@Clas: "fixes overflow legality being a thing"
Created via Iolanthe on Wed, 13 Sep 2023 18:57:36 GMT.

(@Clas) gen8ggph: fixes overflow legality being a thing

---

formats/gen9stabmnm.tour

#placuszek: "free christopher gambitus, inherit csoul ban from stab"
Created via Iolanthe on Sun, 17 Sep 2023 18:57:13 GMT.

(#placuszek) gen9stabmnm: free christopher gambitus, inherit csoul ban from stab

---

formats/gen9mnmlc.tour

%TheTrueLtaker: "banning dunsparce and restricting yanma"
Created via Iolanthe on Mon, 18 Sep 2023 03:36:16 GMT.

(%TheTrueLtaker) gen9mnmlc: banning dunsparce and restricting yanma

---

formats/gen9shaaaredpower.tour
metadata/list.txt

%TheTrueLtaker: "updated to fit better with the current shared power bans and unbans"
Created via Iolanthe on Wed, 20 Sep 2023 12:28:16 GMT.

(%TheTrueLtaker) gen9shaaaredpower: updated to fit better with the current shared power bans and unbans

---

formats/gen9stabmnm.tour

#placuszek: "ban normals"
Created via Iolanthe on Sun, 24 Sep 2023 21:15:18 GMT.

(#placuszek) gen9stabmnm: ban normals

---

formats/gen9camobh.tour
metadata/list.txt

%TheTrueLtaker: "uploading tour code to iolanthe"
Created via Iolanthe on Tue, 10 Oct 2023 00:47:55 GMT.

(%TheTrueLtaker) gen9camobh: uploading tour code to iolanthe

---

formats/gen9mightymega.tour
metadata/list.txt

%TheTrueLtaker: "adding code to iolanthe"
Created via Iolanthe on Mon, 16 Oct 2023 20:00:19 GMT.

(%TheTrueLtaker) gen9mightymega: adding code to iolanthe

---

formats/gen9camobh.tour

%TheTrueLtaker: "banning vcreate and  Mega Alakazam"
Created via Iolanthe on Fri, 20 Oct 2023 01:19:34 GMT.

(%TheTrueLtaker) gen9camobh: banning vcreate and  Mega Alakazam

---

formats/gen9aaaubers.tour

%Kinetic1000 ♆: "idk"
Created via Iolanthe on Sun, 29 Oct 2023 03:37:31 GMT.

(%Kinetic1000 ♆) gen9aaaubers: idk

---

formats/gen9ubersff.tour
metadata/list.txt

%TheTrueLtaker: "banning ngas and caly-s"
Created via Iolanthe on Thu, 02 Nov 2023 02:06:24 GMT.

(%TheTrueLtaker) gen9ubersff: banning ngas and caly-s

---

formats/gen9capce.tour
metadata/list.txt

%Kinetic1000 ♆: "add CAP + CE"
Created via Iolanthe on Sun, 05 Nov 2023 04:52:35 GMT.

(%Kinetic1000 ♆) gen9capce: add CAP + CE

---

formats/gen9mnmlc.tour

@Clas: "gligar + buizel restrict + other missed issues"
Created via Iolanthe on Tue, 14 Nov 2023 12:41:45 GMT.

(@Clas) gen9mnmlc: gligar + buizel restrict + other missed issues

---

formats/gen9ffubers.tour

#placuszek: "ban magpull"
Created via Iolanthe on Wed, 15 Nov 2023 19:06:40 GMT.

(#placuszek) gen9ffubers: ban magpull

---

formats/gen9abcuu.tour
formats/gen9abcuup.tour
metadata/aliases.txt
metadata/list.txt

%Akoof: "new code"
Created via Iolanthe on Mon, 20 Nov 2023 19:58:41 GMT.

(%Akoof) gen9abcuup: new code

---

formats/gen9inhcup.tour
metadata/list.txt

%TheTrueLtaker: "adding to iolanthe"
Created via Iolanthe on Fri, 24 Nov 2023 23:29:38 GMT.

(%TheTrueLtaker) gen9inhcup: adding to iolanthe

---

formats/gen9gglc.tour

%TheTrueLtaker: "fixing a typo"
Created via Iolanthe on Thu, 30 Nov 2023 01:46:38 GMT.

(%TheTrueLtaker) gen9gglc: fixing a typo

---

formats/gen9chaos1v1.tour
metadata/list.txt

%Hisnowi guy %◕‿‿◕%: "New Pr"
Created via Iolanthe on Sun, 10 Dec 2023 16:50:00 GMT.

(%Hisnowi guy %◕‿‿◕%) gen9chaos1v1: New Pr

---

.github/workflows/test.yml
test/create-custom-tests.js

commit 08332cb1baf507b43532f831f3160529a1edde05
Author: WeWuzNidokangz <43294696+WeWuzNidokangz@users.noreply.github.com>
Date:   Thu Jan 4 12:10:38 2024 +0900
Sandbox mirror/split ci (#4)
* Implement Tour Code CI (#421)
* Squashed commit of the following:
commit 8404fb4230c41ac30a7adc70c717812deee4d8b6
Merge: 57536c4 e0b2d8d
Author: WeWuzNidokangz <43294696+WeWuzNidokangz@users.noreply.github.com>
Date:   Tue Jan 2 18:51:47 2024 +0900
Merge pull request #3 from OperationTourCode/SandboxMirror/testPR
Sandbox mirror/test pr
commit e0b2d8d34cbe6d4eec64e1d6ffb3447dfcc41845
Author: WeWuzNidokangz <43294696+WeWuzNidokangz@users.noreply.github.com>
Date:   Tue Jan 2 18:48:49 2024 +0900
Better order
commit 6fffd43b954749e9ae8ec228fedba49096f9e145
Author: WeWuzNidokangz …

CI: In PRs, only check altered tours

---

formats/gen9fortereevochaos.tour

%Akoof: "changing the wall from BT to Bonus Type for clear info"
Created via Iolanthe on Fri, 05 Jan 2024 17:53:20 GMT.

(%Akoof) gen9fortereevochaos: changing the wall from BT to Bonus Type for clear info

---

formats/gen9mnmlc.tour

@Clas: "restricts duraludon"
Created via Iolanthe on Sun, 14 Jan 2024 21:12:43 GMT.

(@Clas) gen9mnmlc: restricts duraludon

---

formats/gen9brokencup1v1.tour
metadata/list.txt

#CringeMeta: "adds code for format"
Created via Iolanthe on Fri, 26 Jan 2024 15:23:41 GMT.

(#CringeMeta) gen9brokencup1v1: adds code for format

---

formats/gen9stabubers.tour

@TheTrueLtaker: "new council bans"
Created via Iolanthe on Sun, 28 Jan 2024 15:52:33 GMT.

(@TheTrueLtaker) gen9stabubers: new council bans

---

formats/gen9doublesungodlygift.tour
metadata/list.txt

@Clas: "adds code"
Created via Iolanthe on Mon, 29 Jan 2024 15:43:12 GMT.

(@Clas) gen9doublesungodlygift: adds code

---

formats/gen9mnmlc.tour

@TheTrueLtaker: "restricting elekid"
Created via Iolanthe on Sun, 11 Feb 2024 17:50:16 GMT.

(@TheTrueLtaker) gen9mnmlc: restricting elekid

---

formats/gen9mnmlc.tour

@Clas: "bans duraludon"
Created via Iolanthe on Thu, 22 Feb 2024 21:08:57 GMT.

(@Clas) gen9mnmlc: bans duraludon

---

formats/gen9mnmlc.tour

@Clas: "actually bans duraludon"
Created via Iolanthe on Sun, 03 Mar 2024 18:29:44 GMT.

(@Clas) gen9mnmlc: actually bans duraludon

---

formats/gen9mnmlc.tour

@Clas: "unbans and restricts girafarig"
Created via Iolanthe on Fri, 08 Mar 2024 22:16:24 GMT.

(@Clas) gen9mnmlc: unbans and restricts girafarig

---

formats/gen9mnmlc.tour

@Clas: "restricts mienfoo + holtorb"
Created via Iolanthe on Sat, 16 Mar 2024 15:15:59 GMT.

(@Clas) gen9mnmlc: restricts mienfoo + holtorb

---

formats/gen9pokelc.tour
metadata/list.txt

@TheTrueLtaker: "adding code to iolanthe"
Created via Iolanthe on Fri, 22 Mar 2024 20:37:28 GMT.

(@TheTrueLtaker) gen9pokelc: adding code to iolanthe

---

formats/gen9stabubers.tour

@TheTrueLtaker: "updating code"
Created via Iolanthe on Wed, 27 Mar 2024 21:21:53 GMT.

(@TheTrueLtaker) gen9stabubers: updating code

---

formats/gen9tsmnm.tour
metadata/list.txt

@TheTrueLtaker: "adding code to iolanthe"
Created via Iolanthe on Thu, 04 Apr 2024 16:36:33 GMT.

(@TheTrueLtaker) gen9tsmnm: adding code to iolanthe

---

formats/gen9mnmlc.tour

@Clas: "adds hub link"
Created via Iolanthe on Fri, 12 Apr 2024 21:20:42 GMT.

(@Clas) gen9mnmlc: adds hub link

---

formats/gen9ggmnm.tour

@Clas: "updates code"
Created via Iolanthe on Fri, 19 Apr 2024 20:19:54 GMT.

(@Clas) gen9ggmnm: updates code

---

formats/gen9mnmlc.tour

@Clas: "restricts gastly + pawniard"
Created via Iolanthe on Tue, 30 Apr 2024 16:35:15 GMT.

(@Clas) gen9mnmlc: restricts gastly + pawniard

---

formats/gen9tsabcamo.tour
formats/gen9tsplitstabcamo.tour
metadata/list.txt

@banded body press: "because"
Created via Iolanthe on Sat, 04 May 2024 17:13:33 GMT.

(@banded body press) gen9tsabcamo: because

---

formats/gen9tsplitstabcamo.tour

@Banded Body Press: "Pincurchin"
Created via Iolanthe on Fri, 10 May 2024 16:51:35 GMT.

(@Banded Body Press) gen9tsplitstabcamo: Pincurchin

---

formats/gen9tsplitstabcamo.tour

@Banded Body Press: "pull request name"
Created via Iolanthe on Sun, 26 May 2024 22:42:54 GMT.

(@Banded Body Press) gen9tsplitstabcamo: pull request name

---

formats/gen9tradeabilities.tour
metadata/list.txt

@Clas: "adds trademarked pokebilities"
Created via Iolanthe on Thu, 30 May 2024 18:24:37 GMT.

(@Clas) gen9tradeabilities: adds trademarked pokebilities

---

formats/gen9tradeabilities.tour

@banded body press: "hydrapple nerf"
Created via Iolanthe on Sat, 01 Jun 2024 14:21:16 GMT.

(@banded body press) gen9tradeabilities: hydrapple nerf

---

formats/gen9tsplitstabcamo.tour

@Banded Body Press: "grahhh"
Created via Iolanthe on Sun, 02 Jun 2024 22:05:26 GMT.

(@Banded Body Press) gen9tsplitstabcamo: grahhh

---

formats/gen9tradeabilities.tour

@Banded Body Press: "jdjkabc"
Created via Iolanthe on Sun, 02 Jun 2024 17:36:21 GMT.

(@Banded Body Press) gen9tradeabilities: jdjkabc

---

formats/gen9tradeabilities.tour

@Clas: "updates code"
Created via Iolanthe on Sun, 09 Jun 2024 01:58:36 GMT.

(@Clas) gen9tradeabilities: updates code

---

formats/gen9tradeabilities.tour

#RICEMAN: "Update Tradeabilities banlist"
Created via Iolanthe on Thu, 20 Jun 2024 00:42:22 GMT.

(#RICEMAN) gen9tradeabilities: Update Tradeabilities banlist

---

formats/gen9mnmlc.tour

@Clas: "reunbans red orb"
Created via Iolanthe on Thu, 20 Jun 2024 16:30:38 GMT.

(@Clas) gen9mnmlc: reunbans red orb

---

formats/gen9tsaaa.tour

#RICEMAN: "Ban Regigigas from TSAAA"
Created via Iolanthe on Mon, 24 Jun 2024 03:55:06 GMT.

(#RICEMAN) gen9tsaaa: Ban Regigigas from TSAAA

---

formats/gen9tradeabilities.tour

@Banded Body Press: "idk"
Created via Iolanthe on Sat, 29 Jun 2024 19:35:20 GMT.

(@Banded Body Press) gen9tradeabilities: idk

---

formats/gen9tradeabilities.tour

@Banded Body Press: "fart noise"
Created via Iolanthe on Wed, 03 Jul 2024 19:03:33 GMT.

(@Banded Body Press) gen9tradeabilities: fart noise

---

formats/gen9tradeabilities.tour

#RICEMAN: "Kingdra Ban"
Created via Iolanthe on Tue, 16 Jul 2024 02:36:41 GMT.

(#RICEMAN) gen9tradeabilities: Kingdra Ban

---

formats/gen9tradeabilities.tour

%Pure Hackmons: "regieleki ban"
Created via Iolanthe on Wed, 17 Jul 2024 17:51:09 GMT.

(%Pure Hackmons) gen9tradeabilities: regieleki ban

---

formats/gen9tradeabilities.tour

@TheTrueLtaker: "banning bear +wish and stun spore restrict"
Created via Iolanthe on Fri, 19 Jul 2024 00:00:29 GMT.

(@TheTrueLtaker) gen9tradeabilities: banning bear +wish and stun spore restrict

---

formats/gen9tradeabilities.tour

@TheTrueLtaker: "banning screens and belly drum freeing azumarill"
Created via Iolanthe on Sat, 20 Jul 2024 14:42:03 GMT.

(@TheTrueLtaker) gen9tradeabilities: banning screens and belly drum freeing azumarill

---

formats/gen9tsaaa.tour

@TheTrueLtaker: "the end of the longhiep era(no more furscales)"
Created via Iolanthe on Sat, 27 Jul 2024 21:57:16 GMT.

(@TheTrueLtaker) gen9tsaaa: the end of the longhiep era(no more furscales)

---

formats/gen9mnmlc.tour

@Clas: "restricts aipom"
Created via Iolanthe on Sat, 03 Aug 2024 13:45:48 GMT.

(@Clas) gen9mnmlc: restricts aipom

---

formats/gen9tsaaa.tour

#RICEMAN: "Ban O-pulse Revival Blessing and Hoopa U"
Created via Iolanthe on Thu, 08 Aug 2024 05:17:16 GMT.

(#RICEMAN) gen9tsaaa: Ban O-pulse Revival Blessing and Hoopa U

---

formats/gen9aaaubers.tour

%Kinetic: "slaking was banned"
Created via Iolanthe on Sat, 10 Aug 2024 00:58:24 GMT.

(%Kinetic) gen9aaaubers: slaking was banned

---

formats/gen9mnmlc.tour

#Clas: "bans cutiefly"
Created via Iolanthe on Sat, 10 Aug 2024 11:09:56 GMT.

(#Clas) gen9mnmlc: bans cutiefly

---

formats/gen9revmnm.tour

#Clas: "updates code"
Created via Iolanthe on Sat, 17 Aug 2024 15:45:59 GMT.

(#Clas) gen9revmnm: updates code

---

formats/gen9aaaubers.tour

#Clas: "bans mpull"
Created via Iolanthe on Sat, 24 Aug 2024 20:31:46 GMT.

(#Clas) gen9aaaubers: bans mpull

---

formats/gen9foxonlyfd.tour
metadata/list.txt

@TheTrueLtaker: "adding code back to iolanthe"
Created via Iolanthe on Sun, 25 Aug 2024 13:35:42 GMT.

(@TheTrueLtaker) gen9foxonlyfd: adding code back to iolanthe

---

formats/gen9mnmlc.tour

@TheTrueLtaker: "updating to tpp code"
Created via Iolanthe on Mon, 02 Sep 2024 23:57:16 GMT.

(@TheTrueLtaker) gen9mnmlc: updating to tpp code

---

formats/gen9franticpotential.tour
metadata/list.txt

@TheTrueLtaker: "adding code to iolanthe"
Created via Iolanthe on Tue, 03 Sep 2024 17:43:23 GMT.

(@TheTrueLtaker) gen9franticpotential: adding code to iolanthe

---

formats/gen9stabubers.tour

@TheTrueLtaker: "freeing flutter mane"
Created via Iolanthe on Wed, 04 Sep 2024 16:25:18 GMT.

(@TheTrueLtaker) gen9stabubers: freeing flutter mane

---

formats/gen9spaaa.tour

@TheTrueLtaker: "banning huge and pure power"
Created via Iolanthe on Sun, 15 Sep 2024 19:14:11 GMT.

(@TheTrueLtaker) gen9spaaa: banning huge and pure power

---

formats/gen9pokeinh.tour

@TheTrueLtaker: "fixing my mistakes"
Created via Iolanthe on Sun, 22 Sep 2024 22:26:25 GMT.

(@TheTrueLtaker) gen9pokeinh: fixing my mistakes

---

formats/gen9yugioh.tour
metadata/list.txt

@TheTrueLtaker: "adding code"
Created via Iolanthe on Wed, 16 Oct 2024 02:50:46 GMT.

(@TheTrueLtaker) gen9yugioh: adding code

---

formats/gen9yugioh.tour

@TheTrueLtaker: "restricts+neater code"
Created via Iolanthe on Thu, 24 Oct 2024 15:48:41 GMT.

(@TheTrueLtaker) gen9yugioh: restricts+neater code

---

formats/gen9aaaubers.tour

@TheTrueLtaker: "no more 1ac"
Created via Iolanthe on Fri, 01 Nov 2024 01:05:21 GMT.

(@TheTrueLtaker) gen9aaaubers: no more 1ac

---

formats/gen9megaconverge.tour

@Banded Body Press: "Belly Drum 1ac"
Created via Iolanthe on Fri, 28 Feb 2025 21:08:30 GMT.

(@Banded Body Press) gen9megaconverge: Belly Drum 1ac

---

formats/gen9randbtas.tour

#Clas: "adds !tier mayhem"
Created via Iolanthe on Mon, 31 Mar 2025 09:04:08 GMT.

(#Clas) gen9randbtas: adds !tier mayhem

---

formats/gen9aaalc.tour

#Clas: "fixes legalities"
Created via Iolanthe on Fri, 25 Apr 2025 19:58:19 GMT.

(#Clas) gen9aaalc: fixes legalities

---

formats/gen9bnbgg.tour
metadata/list.txt

#Banded Body Press: "newww"
Created via Iolanthe on Mon, 28 Apr 2025 23:34:16 GMT.

(#Banded Body Press) gen9bnbgg: newww

---

formats/gen9bnbgg.tour

#Banded Body Press: "skarm restrict"
Created via Iolanthe on Thu, 08 May 2025 15:48:02 GMT.

(#Banded Body Press) gen9bnbgg: skarm restrict

---

formats/gen9randbtas.tour

#Clas: "adds datapreview"
Created via Iolanthe on Sun, 08 Jun 2025 16:39:54 GMT.

(#Clas) gen9randbtas: adds datapreview

---

formats/gen9brokenmayhem.tour

#TheTrueLtaker: "wonder guard is dumb"
Created via Iolanthe on Fri, 25 Jul 2025 00:48:05 GMT.

(#TheTrueLtaker) gen9brokenmayhem: wonder guard is dumb

---

formats/gen9yugioh.tour

#TheTrueLtaker: "trace bites the bullet"
Created via Iolanthe on Fri, 01 Aug 2025 19:07:14 GMT.

(#TheTrueLtaker) gen9yugioh: trace bites the bullet

---

formats/gen9mixnboosted.tour
metadata/list.txt

@pechanerd: "mnm bnb code"
Created via Iolanthe on Mon, 04 Aug 2025 16:42:40 GMT.

(@pechanerd) gen9mixnboosted: mnm bnb code

---

formats/gen9mixnboosted.tour

@pechanerd: "mnb eviolite ban"
Created via Iolanthe on Tue, 05 Aug 2025 16:54:44 GMT.

(@pechanerd) gen9mixnboosted: mnb eviolite ban

---

formats/gen9ggvgc.tour
formats/gen9vggc.tour
metadata/aliases.txt
metadata/list.txt

#Clas: "adds code"
Created via Iolanthe on Wed, 24 Sep 2025 20:42:34 GMT.

(#Clas) gen9ggvgc: adds code

---

formats/gen9ggvgc.tour

#Clas: "updates code to ban pphp"
Created via Iolanthe on Fri, 26 Sep 2025 22:09:19 GMT.

(#Clas) gen9ggvgc: updates code to ban pphp
